### ISSUE TITLE
Booster Corrector Model02 Simulation I=9A

### ISSUE THREAD

**Issue by LuanaVilela** [lnls-ima/bo-correctors#1]
CH (renamed):
 bo-correctors/model-02/simulation/magnetic/2016-11-28_Corrector_Model02_Sim_CH_X=-20_20mm_Z=-300_300mm_Imc=9A.txt 

CV:
 bo-correctors/model-02/simulation/magnetic/2017-01-16_Corrector_Model02_Sim_CV_X=-20_20mm_Z=-300_300mm_Imc=9A.txt

**Comment by xresende** [comment]
fmaps for CH and CV orientations were analyzed. multipoles are all small.
